/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : GPTA.c
**     Project     : ProcessorExpert
**     Processor   : MKL26Z256VLH4
**     Component   : GPIO_LDD
**     Version     : Component 01.128, Driver 01.06, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-05-13, 19:31, # CodeGen: 69
**     Abstract    :
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : GPTA
**          Port                                           : PTA
**          Port width                                     : 32 bits
**          Mask of allocated pins                         : 3020
**          Interrupt service/event                        : Disabled
**          Bit fields                                     : 3
**            Bit field                                    : 
**              Field name                                 : PTA5_LED2
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTA5/USB_CLKIN/TPM0_CH2/I2S0_TX_BCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTA12_LED3
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTA12/TPM1_CH0/I2S0_TXD0
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTA13_LED4
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTA13/TPM1_CH1/I2S0_TX_FS
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**          Initialization                                 : 
**            Auto initialization                          : yes
**            Event mask                                   : 
**              OnPortEvent                                : Disabled
**     Contents    :
**         Init            - LDD_TDeviceData* GPTA_Init(LDD_TUserData *UserDataPtr);
**         SetFieldValue   - void GPTA_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         GetFieldValue   - GPTA_TFieldValue GPTA_GetFieldValue(LDD_TDeviceData *DeviceDataPtr,...
**         ClearFieldBits  - void GPTA_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         SetFieldBits    - void GPTA_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         ToggleFieldBits - void GPTA_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file GPTA.c
** @version 01.06
** @brief
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup GPTA_module GPTA module documentation
**  @{
*/         

/* MODULE GPTA. */

#include "GPTA.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "IO_Map.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  LDD_TUserData *UserData;             /* RTOS device data structure */
} GPTA_TDeviceData, *GPTA_TDeviceDataPtr; /* Device data structure type */
/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static GPTA_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/*
** ===================================================================
**     Method      :  GPTA_Init (component GPIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* GPTA_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  GPTA_TDeviceData *DeviceDataPrv;

  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  /* Save RTOS Device structure */
  DeviceDataPrv->UserData = UserDataPtr; /* Store the RTOS device structure */
  /* GPIOA_PDOR: PDO&=~0x3020 */
  GPIOA_PDOR &= (uint32_t)~(uint32_t)(GPIO_PDOR_PDO(0x3020));                                   
  /* GPIOA_PDDR: PDD|=0x3020 */
  GPIOA_PDDR |= GPIO_PDDR_PDD(0x3020);                                   
  /* Initialization of Port Control registers */
  /* PORTA_PCR5: ISF=0,MUX=1 */
  PORTA_PCR5 = (uint32_t)((PORTA_PCR5 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTA_PCR12: ISF=0,MUX=1 */
  PORTA_PCR12 = (uint32_t)((PORTA_PCR12 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06)
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));                                  
  /* PORTA_PCR13: ISF=0,MUX=1 */
  PORTA_PCR13 = (uint32_t)((PORTA_PCR13 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06)
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));                                  
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_GPTA_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv);
}

/*
** ===================================================================
**     Method      :  GPTA_SetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the output data value of the specified bit
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Value           - Aligned data value to writting to the
**                           specified bit field. The bit 0 corresponds
**                           with the pin which has index 0 within the
**                           given bit field, the bit 1 corresponds with
**                           the pin which has index 1 within the given
**                           bit field, etc.
*/
/* ===================================================================*/
void GPTA_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTA_TFieldValue Value)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTA5_LED2: {                  /* bit field #0 */
      GPIO_PDD_SetPortDataOutput(GPTA_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTA_MODULE_BASE_ADDRESS)
          & ((GPTA_TPortValue)(~((GPTA_TPortValue)GPTA_PTA5_LED2_MASK)))
        )
        | (
          ((GPTA_TPortValue)(Value << GPTA_PTA5_LED2_START_BIT))
          & ((GPTA_TPortValue)GPTA_PTA5_LED2_MASK)
        )
      );
      break;
    }
    case PTA12_LED3: {                 /* bit field #1 */
      GPIO_PDD_SetPortDataOutput(GPTA_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTA_MODULE_BASE_ADDRESS)
          & ((GPTA_TPortValue)(~((GPTA_TPortValue)GPTA_PTA12_LED3_MASK)))
        )
        | (
          ((GPTA_TPortValue)(Value << GPTA_PTA12_LED3_START_BIT))
          & ((GPTA_TPortValue)GPTA_PTA12_LED3_MASK)
        )
      );
      break;
    }
    case PTA13_LED4: {                 /* bit field #2 */
      GPIO_PDD_SetPortDataOutput(GPTA_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTA_MODULE_BASE_ADDRESS)
          & ((GPTA_TPortValue)(~((GPTA_TPortValue)GPTA_PTA13_LED4_MASK)))
        )
        | (
          ((GPTA_TPortValue)(Value << GPTA_PTA13_LED4_START_BIT))
          & ((GPTA_TPortValue)GPTA_PTA13_LED4_MASK)
        )
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  GPTA_GetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current input data of the specified
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to reading. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @return
**                         - Aligned current port input value masked for
**                           allocated pins of the field. The bit 0
**                           corresponds with the pin which has index 0
**                           within the given bit field, the bit 1
**                           corresponds with the pin which has index 1
**                           within the given bit field, etc.
*/
/* ===================================================================*/
GPTA_TFieldValue GPTA_GetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTA5_LED2: {                  /* bit field #0 */
      return
        (GPTA_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTA_MODULE_BASE_ADDRESS)
            & (GPTA_TPortValue)GPTA_PTA5_LED2_MASK
          )
          >> GPTA_PTA5_LED2_START_BIT
        );
    }
    case PTA12_LED3: {                 /* bit field #1 */
      return
        (GPTA_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTA_MODULE_BASE_ADDRESS)
            & (GPTA_TPortValue)GPTA_PTA12_LED3_MASK
          )
          >> GPTA_PTA12_LED3_START_BIT
        );
    }
    case PTA13_LED4: {                 /* bit field #2 */
      return
        (GPTA_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTA_MODULE_BASE_ADDRESS)
            & (GPTA_TPortValue)GPTA_PTA13_LED4_MASK
          )
          >> GPTA_PTA13_LED4_START_BIT
        );
    }
    default:
      break;                           /* Invalid BitField is not treated, result is undefined */
  } /* switch (Field) */
  return (GPTA_TFieldValue)0U;
}

/*
** ===================================================================
**     Method      :  GPTA_ClearFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the inactive level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           inactive level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTA_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTA_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTA5_LED2: {                  /* bit field #0 */
      GPIO_PDD_ClearPortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA5_LED2_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA5_LED2_START_BIT))
      );
      break;
    }
    case PTA12_LED3: {                 /* bit field #1 */
      GPIO_PDD_ClearPortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA12_LED3_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA12_LED3_START_BIT))
      );
      break;
    }
    case PTA13_LED4: {                 /* bit field #2 */
      GPIO_PDD_ClearPortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA13_LED4_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA13_LED4_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  GPTA_SetFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the active level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           active level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTA_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTA_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTA5_LED2: {                  /* bit field #0 */
      GPIO_PDD_SetPortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA5_LED2_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA5_LED2_START_BIT))
      );
      break;
    }
    case PTA12_LED3: {                 /* bit field #1 */
      GPIO_PDD_SetPortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA12_LED3_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA12_LED3_START_BIT))
      );
      break;
    }
    case PTA13_LED4: {                 /* bit field #2 */
      GPIO_PDD_SetPortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA13_LED4_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA13_LED4_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  GPTA_ToggleFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method inverts the specified bits of the specified bit
**         field to other level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to inverting the
**                           current level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTA_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTA_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTA5_LED2: {                  /* bit field #0 */
      GPIO_PDD_TogglePortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA5_LED2_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA5_LED2_START_BIT))
      );
      break;
    }
    case PTA12_LED3: {                 /* bit field #1 */
      GPIO_PDD_TogglePortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA12_LED3_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA12_LED3_START_BIT))
      );
      break;
    }
    case PTA13_LED4: {                 /* bit field #2 */
      GPIO_PDD_TogglePortDataOutputMask(GPTA_MODULE_BASE_ADDRESS,
        ((GPTA_TPortValue)GPTA_PTA13_LED4_MASK)
        & ((GPTA_TPortValue)(Mask << GPTA_PTA13_LED4_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/* END GPTA. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
