/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : GPTC.c
**     Project     : ProcessorExpert
**     Processor   : MKL26Z256VLH4
**     Component   : GPIO_LDD
**     Version     : Component 01.128, Driver 01.06, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-04-15, 01:27, # CodeGen: 60
**     Abstract    :
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : GPTC
**          Port                                           : PTC
**          Port width                                     : 32 bits
**          Mask of allocated pins                         : 75F
**          Interrupt service/event                        : Disabled
**          Bit fields                                     : 9
**            Bit field                                    : 
**              Field name                                 : PTC0_GPS_WIFI_SEL
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/audioUSB_SOF_OUT/CMP0_OUT/I2S0_TXD0
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC1_LED5
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC2_LED6
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC3_LED7
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC4_WIFI_ASSEMBLY
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC6_PTT
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC8_WIFI_WAKEUP
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4/I2S0_MCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC9_WIFI_EN
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC10_WIFI_RST
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC10/I2C1_SCL/I2S0_RX_FS
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 1
**                  Initial pin event                      : Disabled
**          Initialization                                 : 
**            Auto initialization                          : yes
**            Event mask                                   : 
**              OnPortEvent                                : Disabled
**     Contents    :
**         Init            - LDD_TDeviceData* GPTC_Init(LDD_TUserData *UserDataPtr);
**         SetFieldValue   - void GPTC_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         GetFieldValue   - GPTC_TFieldValue GPTC_GetFieldValue(LDD_TDeviceData *DeviceDataPtr,...
**         ClearFieldBits  - void GPTC_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         SetFieldBits    - void GPTC_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         ToggleFieldBits - void GPTC_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file GPTC.c
** @version 01.06
** @brief
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup GPTC_module GPTC module documentation
**  @{
*/         

/* MODULE GPTC. */

#include "GPTC.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "IO_Map.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  LDD_TUserData *UserData;             /* RTOS device data structure */
} GPTC_TDeviceData, *GPTC_TDeviceDataPtr; /* Device data structure type */
/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static GPTC_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/*
** ===================================================================
**     Method      :  GPTC_Init (component GPIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* GPTC_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  GPTC_TDeviceData *DeviceDataPrv;

  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  /* Save RTOS Device structure */
  DeviceDataPrv->UserData = UserDataPtr; /* Store the RTOS device structure */
  /* GPIOC_PDOR: PDO&=~0x030F,PDO|=0x0400 */
  GPIOC_PDOR = (uint32_t)((GPIOC_PDOR & (uint32_t)~(uint32_t)(
                GPIO_PDOR_PDO(0x030F)
               )) | (uint32_t)(
                GPIO_PDOR_PDO(0x0400)
               ));                                  
  /* GPIOC_PDDR: PDD&=~0x50,PDD|=0x070F */
  GPIOC_PDDR = (uint32_t)((GPIOC_PDDR & (uint32_t)~(uint32_t)(
                GPIO_PDDR_PDD(0x50)
               )) | (uint32_t)(
                GPIO_PDDR_PDD(0x070F)
               ));                                  
  /* Initialization of Port Control registers */
  /* PORTC_PCR0: ISF=0,MUX=1 */
  PORTC_PCR0 = (uint32_t)((PORTC_PCR0 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTC_PCR1: ISF=0,MUX=1 */
  PORTC_PCR1 = (uint32_t)((PORTC_PCR1 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTC_PCR2: ISF=0,MUX=1 */
  PORTC_PCR2 = (uint32_t)((PORTC_PCR2 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTC_PCR3: ISF=0,MUX=1 */
  PORTC_PCR3 = (uint32_t)((PORTC_PCR3 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTC_PCR4: ISF=0,MUX=1 */
  PORTC_PCR4 = (uint32_t)((PORTC_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTC_PCR6: ISF=0,MUX=1 */
  PORTC_PCR6 = (uint32_t)((PORTC_PCR6 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTC_PCR8: ISF=0,MUX=1 */
  PORTC_PCR8 = (uint32_t)((PORTC_PCR8 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTC_PCR9: ISF=0,MUX=1 */
  PORTC_PCR9 = (uint32_t)((PORTC_PCR9 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));                                  
  /* PORTC_PCR10: ISF=0,MUX=1 */
  PORTC_PCR10 = (uint32_t)((PORTC_PCR10 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06)
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));                                  
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_GPTC_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv);
}

/*
** ===================================================================
**     Method      :  GPTC_SetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the output data value of the specified bit
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Value           - Aligned data value to writting to the
**                           specified bit field. The bit 0 corresponds
**                           with the pin which has index 0 within the
**                           given bit field, the bit 1 corresponds with
**                           the pin which has index 1 within the given
**                           bit field, etc.
*/
/* ===================================================================*/
void GPTC_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTC_TFieldValue Value)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTC0_GPS_WIFI_SEL: {          /* bit field #0 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC0_GPS_WIFI_SEL_MASK)))
        )
        | (
          Value
          & ((GPTC_TPortValue)GPTC_PTC0_GPS_WIFI_SEL_MASK)
        )
      );
      break;
    }
    case PTC1_LED5: {                  /* bit field #1 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC1_LED5_MASK)))
        )
        | (
          ((GPTC_TPortValue)(Value << GPTC_PTC1_LED5_START_BIT))
          & ((GPTC_TPortValue)GPTC_PTC1_LED5_MASK)
        )
      );
      break;
    }
    case PTC2_LED6: {                  /* bit field #2 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC2_LED6_MASK)))
        )
        | (
          ((GPTC_TPortValue)(Value << GPTC_PTC2_LED6_START_BIT))
          & ((GPTC_TPortValue)GPTC_PTC2_LED6_MASK)
        )
      );
      break;
    }
    case PTC3_LED7: {                  /* bit field #3 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC3_LED7_MASK)))
        )
        | (
          ((GPTC_TPortValue)(Value << GPTC_PTC3_LED7_START_BIT))
          & ((GPTC_TPortValue)GPTC_PTC3_LED7_MASK)
        )
      );
      break;
    }
    case PTC4_WIFI_ASSEMBLY: {         /* bit field #4 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC4_WIFI_ASSEMBLY_MASK)))
        )
        | (
          ((GPTC_TPortValue)(Value << GPTC_PTC4_WIFI_ASSEMBLY_START_BIT))
          & ((GPTC_TPortValue)GPTC_PTC4_WIFI_ASSEMBLY_MASK)
        )
      );
      break;
    }
    case PTC6_PTT: {                   /* bit field #5 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC6_PTT_MASK)))
        )
        | (
          ((GPTC_TPortValue)(Value << GPTC_PTC6_PTT_START_BIT))
          & ((GPTC_TPortValue)GPTC_PTC6_PTT_MASK)
        )
      );
      break;
    }
    case PTC8_WIFI_WAKEUP: {           /* bit field #6 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC8_WIFI_WAKEUP_MASK)))
        )
        | (
          ((GPTC_TPortValue)(Value << GPTC_PTC8_WIFI_WAKEUP_START_BIT))
          & ((GPTC_TPortValue)GPTC_PTC8_WIFI_WAKEUP_MASK)
        )
      );
      break;
    }
    case PTC9_WIFI_EN: {               /* bit field #7 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC9_WIFI_EN_MASK)))
        )
        | (
          ((GPTC_TPortValue)(Value << GPTC_PTC9_WIFI_EN_START_BIT))
          & ((GPTC_TPortValue)GPTC_PTC9_WIFI_EN_MASK)
        )
      );
      break;
    }
    case PTC10_WIFI_RST: {             /* bit field #8 */
      GPIO_PDD_SetPortDataOutput(GPTC_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPTC_MODULE_BASE_ADDRESS)
          & ((GPTC_TPortValue)(~((GPTC_TPortValue)GPTC_PTC10_WIFI_RST_MASK)))
        )
        | (
          ((GPTC_TPortValue)(Value << GPTC_PTC10_WIFI_RST_START_BIT))
          & ((GPTC_TPortValue)GPTC_PTC10_WIFI_RST_MASK)
        )
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  GPTC_GetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current input data of the specified
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to reading. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @return
**                         - Aligned current port input value masked for
**                           allocated pins of the field. The bit 0
**                           corresponds with the pin which has index 0
**                           within the given bit field, the bit 1
**                           corresponds with the pin which has index 1
**                           within the given bit field, etc.
*/
/* ===================================================================*/
GPTC_TFieldValue GPTC_GetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTC0_GPS_WIFI_SEL: {          /* bit field #0 */
      return
        (GPTC_TFieldValue)(
          GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
          & (GPTC_TPortValue)GPTC_PTC0_GPS_WIFI_SEL_MASK
        );
    }
    case PTC1_LED5: {                  /* bit field #1 */
      return
        (GPTC_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
            & (GPTC_TPortValue)GPTC_PTC1_LED5_MASK
          )
          >> GPTC_PTC1_LED5_START_BIT
        );
    }
    case PTC2_LED6: {                  /* bit field #2 */
      return
        (GPTC_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
            & (GPTC_TPortValue)GPTC_PTC2_LED6_MASK
          )
          >> GPTC_PTC2_LED6_START_BIT
        );
    }
    case PTC3_LED7: {                  /* bit field #3 */
      return
        (GPTC_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
            & (GPTC_TPortValue)GPTC_PTC3_LED7_MASK
          )
          >> GPTC_PTC3_LED7_START_BIT
        );
    }
    case PTC4_WIFI_ASSEMBLY: {         /* bit field #4 */
      return
        (GPTC_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
            & (GPTC_TPortValue)GPTC_PTC4_WIFI_ASSEMBLY_MASK
          )
          >> GPTC_PTC4_WIFI_ASSEMBLY_START_BIT
        );
    }
    case PTC6_PTT: {                   /* bit field #5 */
      return
        (GPTC_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
            & (GPTC_TPortValue)GPTC_PTC6_PTT_MASK
          )
          >> GPTC_PTC6_PTT_START_BIT
        );
    }
    case PTC8_WIFI_WAKEUP: {           /* bit field #6 */
      return
        (GPTC_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
            & (GPTC_TPortValue)GPTC_PTC8_WIFI_WAKEUP_MASK
          )
          >> GPTC_PTC8_WIFI_WAKEUP_START_BIT
        );
    }
    case PTC9_WIFI_EN: {               /* bit field #7 */
      return
        (GPTC_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
            & (GPTC_TPortValue)GPTC_PTC9_WIFI_EN_MASK
          )
          >> GPTC_PTC9_WIFI_EN_START_BIT
        );
    }
    case PTC10_WIFI_RST: {             /* bit field #8 */
      return
        (GPTC_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPTC_MODULE_BASE_ADDRESS)
            & (GPTC_TPortValue)GPTC_PTC10_WIFI_RST_MASK
          )
          >> GPTC_PTC10_WIFI_RST_START_BIT
        );
    }
    default:
      break;                           /* Invalid BitField is not treated, result is undefined */
  } /* switch (Field) */
  return (GPTC_TFieldValue)0U;
}

/*
** ===================================================================
**     Method      :  GPTC_ClearFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the inactive level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           inactive level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTC_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTC_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTC0_GPS_WIFI_SEL: {          /* bit field #0 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC0_GPS_WIFI_SEL_MASK)
        & Mask
      );
      break;
    }
    case PTC1_LED5: {                  /* bit field #1 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC1_LED5_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC1_LED5_START_BIT))
      );
      break;
    }
    case PTC2_LED6: {                  /* bit field #2 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC2_LED6_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC2_LED6_START_BIT))
      );
      break;
    }
    case PTC3_LED7: {                  /* bit field #3 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC3_LED7_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC3_LED7_START_BIT))
      );
      break;
    }
    case PTC4_WIFI_ASSEMBLY: {         /* bit field #4 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC4_WIFI_ASSEMBLY_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC4_WIFI_ASSEMBLY_START_BIT))
      );
      break;
    }
    case PTC6_PTT: {                   /* bit field #5 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC6_PTT_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC6_PTT_START_BIT))
      );
      break;
    }
    case PTC8_WIFI_WAKEUP: {           /* bit field #6 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC8_WIFI_WAKEUP_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC8_WIFI_WAKEUP_START_BIT))
      );
      break;
    }
    case PTC9_WIFI_EN: {               /* bit field #7 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC9_WIFI_EN_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC9_WIFI_EN_START_BIT))
      );
      break;
    }
    case PTC10_WIFI_RST: {             /* bit field #8 */
      GPIO_PDD_ClearPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC10_WIFI_RST_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC10_WIFI_RST_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  GPTC_SetFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the active level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           active level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTC_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTC_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTC0_GPS_WIFI_SEL: {          /* bit field #0 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC0_GPS_WIFI_SEL_MASK)
        & Mask
      );
      break;
    }
    case PTC1_LED5: {                  /* bit field #1 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC1_LED5_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC1_LED5_START_BIT))
      );
      break;
    }
    case PTC2_LED6: {                  /* bit field #2 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC2_LED6_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC2_LED6_START_BIT))
      );
      break;
    }
    case PTC3_LED7: {                  /* bit field #3 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC3_LED7_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC3_LED7_START_BIT))
      );
      break;
    }
    case PTC4_WIFI_ASSEMBLY: {         /* bit field #4 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC4_WIFI_ASSEMBLY_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC4_WIFI_ASSEMBLY_START_BIT))
      );
      break;
    }
    case PTC6_PTT: {                   /* bit field #5 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC6_PTT_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC6_PTT_START_BIT))
      );
      break;
    }
    case PTC8_WIFI_WAKEUP: {           /* bit field #6 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC8_WIFI_WAKEUP_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC8_WIFI_WAKEUP_START_BIT))
      );
      break;
    }
    case PTC9_WIFI_EN: {               /* bit field #7 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC9_WIFI_EN_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC9_WIFI_EN_START_BIT))
      );
      break;
    }
    case PTC10_WIFI_RST: {             /* bit field #8 */
      GPIO_PDD_SetPortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC10_WIFI_RST_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC10_WIFI_RST_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  GPTC_ToggleFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method inverts the specified bits of the specified bit
**         field to other level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to inverting the
**                           current level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTC_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTC_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case PTC0_GPS_WIFI_SEL: {          /* bit field #0 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC0_GPS_WIFI_SEL_MASK)
        & Mask
      );
      break;
    }
    case PTC1_LED5: {                  /* bit field #1 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC1_LED5_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC1_LED5_START_BIT))
      );
      break;
    }
    case PTC2_LED6: {                  /* bit field #2 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC2_LED6_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC2_LED6_START_BIT))
      );
      break;
    }
    case PTC3_LED7: {                  /* bit field #3 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC3_LED7_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC3_LED7_START_BIT))
      );
      break;
    }
    case PTC4_WIFI_ASSEMBLY: {         /* bit field #4 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC4_WIFI_ASSEMBLY_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC4_WIFI_ASSEMBLY_START_BIT))
      );
      break;
    }
    case PTC6_PTT: {                   /* bit field #5 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC6_PTT_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC6_PTT_START_BIT))
      );
      break;
    }
    case PTC8_WIFI_WAKEUP: {           /* bit field #6 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC8_WIFI_WAKEUP_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC8_WIFI_WAKEUP_START_BIT))
      );
      break;
    }
    case PTC9_WIFI_EN: {               /* bit field #7 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC9_WIFI_EN_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC9_WIFI_EN_START_BIT))
      );
      break;
    }
    case PTC10_WIFI_RST: {             /* bit field #8 */
      GPIO_PDD_TogglePortDataOutputMask(GPTC_MODULE_BASE_ADDRESS,
        ((GPTC_TPortValue)GPTC_PTC10_WIFI_RST_MASK)
        & ((GPTC_TPortValue)(Mask << GPTC_PTC10_WIFI_RST_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/* END GPTC. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
