/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : GPTC.h
**     Project     : ProcessorExpert
**     Processor   : MKL26Z256VLH4
**     Component   : GPIO_LDD
**     Version     : Component 01.128, Driver 01.06, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-04-15, 01:27, # CodeGen: 60
**     Abstract    :
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : GPTC
**          Port                                           : PTC
**          Port width                                     : 32 bits
**          Mask of allocated pins                         : 75F
**          Interrupt service/event                        : Disabled
**          Bit fields                                     : 9
**            Bit field                                    : 
**              Field name                                 : PTC0_GPS_WIFI_SEL
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/audioUSB_SOF_OUT/CMP0_OUT/I2S0_TXD0
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC1_LED5
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC2_LED6
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC3_LED7
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC4_WIFI_ASSEMBLY
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC6_PTT
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC8_WIFI_WAKEUP
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4/I2S0_MCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC9_WIFI_EN
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : PTC10_WIFI_RST
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC10/I2C1_SCL/I2S0_RX_FS
**                  Pin signal                             : 
**                  Initial pin direction                  : Output
**                    Initial output state                 : 1
**                  Initial pin event                      : Disabled
**          Initialization                                 : 
**            Auto initialization                          : yes
**            Event mask                                   : 
**              OnPortEvent                                : Disabled
**     Contents    :
**         Init            - LDD_TDeviceData* GPTC_Init(LDD_TUserData *UserDataPtr);
**         SetFieldValue   - void GPTC_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         GetFieldValue   - GPTC_TFieldValue GPTC_GetFieldValue(LDD_TDeviceData *DeviceDataPtr,...
**         ClearFieldBits  - void GPTC_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         SetFieldBits    - void GPTC_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         ToggleFieldBits - void GPTC_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file GPTC.h
** @version 01.06
** @brief
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup GPTC_module GPTC module documentation
**  @{
*/         

#ifndef __GPTC_H
#define __GPTC_H

/* MODULE GPTC. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "IO_Map.h"
#include "GPIO_PDD.h"
#include "PORT_PDD.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 


/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define GPTC_PRPH_BASE_ADDRESS  0x400FF080U
  
/*! Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods. */
#define GPTC_DeviceData  ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_GPTC_ID))

/* Methods configuration constants - generated for all enabled component's methods */
#define GPTC_Init_METHOD_ENABLED       /*!< Init method of the component GPTC is enabled (generated) */
#define GPTC_SetFieldValue_METHOD_ENABLED /*!< SetFieldValue method of the component GPTC is enabled (generated) */
#define GPTC_GetFieldValue_METHOD_ENABLED /*!< GetFieldValue method of the component GPTC is enabled (generated) */
#define GPTC_ClearFieldBits_METHOD_ENABLED /*!< ClearFieldBits method of the component GPTC is enabled (generated) */
#define GPTC_SetFieldBits_METHOD_ENABLED /*!< SetFieldBits method of the component GPTC is enabled (generated) */
#define GPTC_ToggleFieldBits_METHOD_ENABLED /*!< ToggleFieldBits method of the component GPTC is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */

/* Definition of bit field constants */
#define PTC0_GPS_WIFI_SEL ((LDD_GPIO_TBitField)0)
#define PTC1_LED5 ((LDD_GPIO_TBitField)1)
#define PTC2_LED6 ((LDD_GPIO_TBitField)2)
#define PTC3_LED7 ((LDD_GPIO_TBitField)3)
#define PTC4_WIFI_ASSEMBLY ((LDD_GPIO_TBitField)4)
#define PTC6_PTT ((LDD_GPIO_TBitField)5)
#define PTC8_WIFI_WAKEUP ((LDD_GPIO_TBitField)6)
#define PTC9_WIFI_EN ((LDD_GPIO_TBitField)7)
#define PTC10_WIFI_RST ((LDD_GPIO_TBitField)8)

/* Definition of implementation constants */
#define GPTC_ALLOCATED_PINS_MASK 0x075FU /*!< Mask of all allocated pins from the port */
#define GPTC_MODULE_BASE_ADDRESS FPTC_BASE_PTR /*!< Name of macro used as the base address */
#define GPTC_PORTCONTROL_BASE_ADDRESS PORTC_BASE_PTR /*!< Name of macro used as the base address */
#define GPTC_AVAILABLE_EVENTS_MASK 0x00U /*!< Mask of all available events */
#define GPTC_FIELD_0_PIN_0 LDD_GPIO_PIN_0 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_FIELD_1_PIN_0 LDD_GPIO_PIN_1 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_FIELD_2_PIN_0 LDD_GPIO_PIN_2 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_FIELD_3_PIN_0 LDD_GPIO_PIN_3 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_FIELD_4_PIN_0 LDD_GPIO_PIN_4 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_FIELD_5_PIN_0 LDD_GPIO_PIN_6 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_FIELD_6_PIN_0 LDD_GPIO_PIN_8 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_FIELD_7_PIN_0 LDD_GPIO_PIN_9 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_FIELD_8_PIN_0 LDD_GPIO_PIN_10 /*!< Constant for the pin in the field used in the method ConnectPin */
#define GPTC_PTC0_GPS_WIFI_SEL_START_BIT 0u /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC0_GPS_WIFI_SEL_MASK 0x01u /*!< Mask of the bits allocated by the bit field (within the port) */
#define GPTC_PTC1_LED5_START_BIT 1u    /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC1_LED5_MASK 0x02u      /*!< Mask of the bits allocated by the bit field (within the port) */
#define GPTC_PTC2_LED6_START_BIT 2u    /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC2_LED6_MASK 0x04u      /*!< Mask of the bits allocated by the bit field (within the port) */
#define GPTC_PTC3_LED7_START_BIT 3u    /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC3_LED7_MASK 0x08u      /*!< Mask of the bits allocated by the bit field (within the port) */
#define GPTC_PTC4_WIFI_ASSEMBLY_START_BIT 4u /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC4_WIFI_ASSEMBLY_MASK 0x10u /*!< Mask of the bits allocated by the bit field (within the port) */
#define GPTC_PTC6_PTT_START_BIT 6u     /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC6_PTT_MASK 0x40u       /*!< Mask of the bits allocated by the bit field (within the port) */
#define GPTC_PTC8_WIFI_WAKEUP_START_BIT 8u /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC8_WIFI_WAKEUP_MASK 0x0100u /*!< Mask of the bits allocated by the bit field (within the port) */
#define GPTC_PTC9_WIFI_EN_START_BIT 9u /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC9_WIFI_EN_MASK 0x0200u /*!< Mask of the bits allocated by the bit field (within the port) */
#define GPTC_PTC10_WIFI_RST_START_BIT 10u /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define GPTC_PTC10_WIFI_RST_MASK 0x0400u /*!< Mask of the bits allocated by the bit field (within the port) */
/* Representation of unaligned data value of the port.
   Unsigned integer of proper width depending on the size of the GPIO port allocated.
   Typically the value of n-th bit represents the data for the n-th pin within the port.
   Such value is not abstracted from the physical position of the bits within the port. */
typedef uint32_t GPTC_TPortValue;

/* Representation of right-aligned data value of the bit field.
   Typically the value of n-th bit represents the data of the n-th bit within the bit field (not within the port).
   There are used only so many lowest bits, as it is denoted by the width of the bit field.
   Such value is abstracted from the physical position of the bit field pins within the port.
   Equals to the type <compId>_TPortValue. */
typedef GPTC_TPortValue GPTC_TFieldValue;



/*
** ===================================================================
**     Method      :  GPTC_Init (component GPIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* GPTC_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  GPTC_SetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the output data value of the specified bit
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Value           - Aligned data value to writting to the
**                           specified bit field. The bit 0 corresponds
**                           with the pin which has index 0 within the
**                           given bit field, the bit 1 corresponds with
**                           the pin which has index 1 within the given
**                           bit field, etc.
*/
/* ===================================================================*/
void GPTC_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTC_TFieldValue Value);

/*
** ===================================================================
**     Method      :  GPTC_GetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current input data of the specified
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to reading. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @return
**                         - Aligned current port input value masked for
**                           allocated pins of the field. The bit 0
**                           corresponds with the pin which has index 0
**                           within the given bit field, the bit 1
**                           corresponds with the pin which has index 1
**                           within the given bit field, etc.
*/
/* ===================================================================*/
GPTC_TFieldValue GPTC_GetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field);

/*
** ===================================================================
**     Method      :  GPTC_ClearFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the inactive level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           inactive level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTC_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTC_TFieldValue Mask);

/*
** ===================================================================
**     Method      :  GPTC_SetFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the active level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           active level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTC_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTC_TFieldValue Mask);

/*
** ===================================================================
**     Method      :  GPTC_ToggleFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method inverts the specified bits of the specified bit
**         field to other level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to inverting the
**                           current level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void GPTC_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPTC_TFieldValue Mask);

/* END GPTC. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __GPTC_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
